### ISSUE TITLE
Bacana ;)

### ISSUE THREAD

**Issue by lucasferreira** [renanhrqs/front_end#1]
Jovem Renan,

Agradeço essa entrega e também a presença em sala de aula durante todo esse semestre ;)

Como sugestão aqui eu deixo a possibilidade de tu ter nomeado os arquivos já do jeito certo, tipo index.html, style.css e script.js assim fica mais fácil de visualizar e usar o código aqui do github.

Mas é óbvio que eu consegui testar e verificar teu código, no geral está bacana, layout "diferenciado".

Abraços e tamojunto \o/

**Comment by renanhrqs** [comment]
tamo junto!
